INSERT INTO clientes(name, last_name, email, date) VALUES('Felix','De la Cruz', 'felixtoledo95@gmail.com', '1995-06-11');
INSERT INTO clientes(name, last_name, email, date) VALUES('Alexis','De la Cruz','alexisdct@gmail.com','1988-11-29');
INSERT INTO clientes(name, last_name, email, date) VALUES('Ivan','De la Cruz','ivantoledo1990@gmail.com', '1990-10-27');
INSERT INTO clientes(name, last_name, email, date) VALUES('Cristina','Toledo','toac1959@gmail.com', '1959-05-28');
INSERT INTO clientes(name, last_name, email, date) VALUES('Conrado','De la Cruz','cugc1956@hotmail.com','1956-11-25');
INSERT INTO clientes(name, last_name, email, date) VALUES('Tania M.','Cuellar','monse.cuellar1994@gmail.com','1994-05-19');
INSERT INTO clientes(name, last_name, email, date) VALUES('Brandown','Nájera','brandown_najera@gmail.com','1996-07-11');
INSERT INTO clientes(name, last_name, email, date) VALUES('Jose','Robles','jrobles1993@gmail.com','1993-08-13');
INSERT INTO clientes(name, last_name, email, date) VALUES('Ariana','Criollo','ari_criollo@gmail.com','1995-01-14');
INSERT INTO clientes(name, last_name, email, date) VALUES('Jacqueline','Hernandez','jacquelineho@gmail.com','1993-01-17');
INSERT INTO clientes(name, last_name, email, date) VALUES('Keisi','Miranda','keisimiranda@yahoo.com','2016-10-28');
INSERT INTO clientes(name, last_name, email, date) VALUES('Josh','Fry','jfry@gmail.com','1998-05-17');
INSERT INTO clientes(name, last_name, email, date) VALUES('Rodrigo','Bautista','rodrigo_bautista@gmail.com','1992-08-27');
INSERT INTO clientes(name, last_name, email, date) VALUES('Marco','Bejar','marcobejar1988@gmail.com','1988-03-22');
INSERT INTO clientes(name, last_name, email, date) VALUES('Sergio','Rojas','sergio.rojas1@outlook.com','1991-07-20');